spring:
  r2dbc:
    url: r2dbc:postgresql://localhost:5433/postgres
    username: cnxlabor-exchange
    password: admin
    properties:
      schema: labor-exchange

server:
  port : 8081

springdoc:
  swagger-ui:
    path: /swagger-ui.html
logging:
  level:
    io:
      #netty: TRACE
      #r2dbc.postgresql.QUERY: DEBUG # for queries
      #r2dbc.postgresql.PARAM: DEBUG # for parameters