version: '3.8'
services:
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5433:5432'
    volumes:
      - db:/var/lib/postgresql/data

  exchange:
    build: ..
    environment:
      PROFILE: local
    ports:
      - '8081:8080'

volumes:
  db:
    driver: local